### ISSUE TITLE
Buienradar initiates a Node-Red restart 

### ISSUE THREAD

**Issue by Kapee** [dkijkuit/node-red-contrib-buienradar#1]
A couple of days I have a restart of Node-Red caused by the buienradar node.
See this entry in the syslog of the Rpi3  (/var/log/syslog):

May 10 06:25:05 raspberrypi rsyslogd: [origin software="rsyslogd" swVersion="8.4.2" x-pid="420" x-info="http://www.rsyslog.com"] rsyslogd was HUPed
May 10 07:15:18 raspberrypi Node-RED[3588]: 10 May 07:15:18 - [red] Uncaught Exception:
May 10 07:15:18 raspberrypi rsyslogd0: action 'action 17' resumed (module 'builtin:ompipe') [try http://www.rsyslog.com/e/0 ]
May 10 07:15:18 raspberrypi rsyslogd-2359: action 'action 17' resumed (module 'builtin:ompipe') [try http://www.rsyslog.com/e/2359 ]
May 10 07:15:18 raspberrypi Node-RED[3588]: 10 May 07:15:18 - TypeError: Cannot read property 'childNodes' of undefined
May 10 07:15:18 raspberrypi Node-RED[3588]: at IncomingMessage.<anonymous> (/root/.node-red/node_modules/node-red-contrib-buienradar/buienradar.js:66:46)
May 10 07:15:18 raspberrypi Node-RED[3588]: at emitNone (events.js:91:20)
May 10 07:15:18 raspberrypi Node-RED[3588]: at IncomingMessage.emit (events.js:186:7)
May 10 07:15:18 raspberrypi Node-RED[3588]: at endReadableNT (_stream_readable.js:974:12)
May 10 07:15:18 raspberrypi Node-RED[3588]: at _combinedTickCallback (internal/process/next_tick.js:74:11)
May 10 07:15:18 raspberrypi Node-RED[3588]: at process._tickCallback (internal/process/next_tick.js:98:9)
May 10 07:15:18 raspberrypi systemd[1]: nodered.service: main process exited, code=exited, status=1/FAILURE
May 10 07:15:18 raspberrypi systemd[1]: Unit nodered.service entered failed state.
May 10 07:15:18 raspberrypi systemd[1]: nodered.service holdoff time over, scheduling restart.
May 10 07:15:18 raspberrypi systemd[1]: Stopping Node-RED graphical event wiring tool....
May 10 07:15:18 raspberrypi systemd[1]: Starting Node-RED graphical event wiring tool....
May 10 07:15:18 raspberrypi systemd[1]: Started Node-RED graphical event wiring tool..
May 10 07:15:20 raspberrypi Node-RED[28615]: 10 May 07:15:20 - [info]
May 10 07:15:20 raspberrypi Node-RED[28615]: Welcome to Node-RED
May 10 07:15:20 raspberrypi Node-RED[28615]: ===================

I think most important line: 07:15:18 - TypeError: Cannot read property 'childNodes' of undefined.
Hope the node can be changed and ignoring this error. Or can I catch up this error, not generating a restart?

**Comment by dkijkuit** [comment]
Thank you for pointing this out. Added addtional safety check.
Fixed: fe7c4624a87b0664e7bd58b550458ec6472ca2f7

**Comment by Kapee** [comment]
No problems anymore with this update, thanks
