### ISSUE TITLE
Flow stopped

### ISSUE THREAD

**Issue by coolbox13** [dkijkuit/node-red-contrib-buienradar#14]
Hoi,

Het lijkt erop dat de link met buienradar sinds gisterenavond 23.20 niet meer met nieuwe berichten doorkomt. Er komen nog wel berichten conform het interval maar telkens dezelfde dus.
Bij deze een kopie van het laatst binnengekomen bericht;

{"stationcode":"6260","stationnaam":"Meetstation De Bilt","datum":"04/15/2020 23:20:00","luchtvochtigheid":"74","temperatuurGC":"8.4","windsnelheidMS":"1.5","windsnelheidBF":"1","windrichtingGR":"34","windrichting":"NO","luchtdruk":"1020.8","zichtmeters":"18500","windstotenMS":"2.4","regenMMPU":"-","zonintensiteitWM2":"-","icoonactueel":"https://www.buienradar.nl/resources/images/icons/weather/30x30/cc.png","icoonzin":"Zwaar bewolkt"}

Heb je node al eens verwijderd en uninstalled en weer erin gezet maar dat hielp niet. Restart van Node-red ook niet. Heb je nog meer suggesties?
Alvast bedankt! (super node trouwens!!..:))
Herman

**Comment by dkijkuit** [comment]
Ligt niet aan de node, buienradar levert zelf geen nieuwe data aan.
Zie: [https://data.buienradar.nl/1.0/feed/xml](https://data.buienradar.nl/1.0/feed/xml)

**Comment by coolbox13** [comment]
Ik zag dat buienradar een versie 2.0 live heeft staan. Nu in jason formaat.
url is https://data.buienradar.nl/2.0/feed/json

Deze (simpele) node-red flow geeft een object waaruit de diverse stations zijn te halen. Niet zo mooi als uit jou kant en klare versie maar werkbaar.

[{"id":"ee5ec95b.d2b468","type":"inject","z":"c371a104.bf6be","name":"make request","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":130,"y":600,"wires":[["6757076d.a2c7b8"]]},{"id":"6757076d.a2c7b8","type":"http request","z":"c371a104.bf6be","name":"","method":"GET","ret":"txt","paytoqs":false,"url":"https://data.buienradar.nl/2.0/feed/json","tls":"","persist":false,"proxy":"","authType":"","x":310,"y":600,"wires":[["9594244b.40a9f8"]]},{"id":"ad480648.d5d1b8","type":"debug","z":"c371a104.bf6be","name":"","active":true,"console":"false","complete":"false","x":710,"y":600,"wires":[]},{"id":"9594244b.40a9f8","type":"json","z":"c371a104.bf6be","name":"","property":"payload","action":"","pretty":false,"x":510,"y":600,"wires":[["ad480648.d5d1b8"]]}]

**Comment by coolbox13** [comment]
Bijgaand een flow om actual weerstation in een msg te krijgen. Voor mij is alleen De Bilt relevant en eea is absoluut niet elegant, hufterproof etc gemaakt maar werkbaar op korte termijn. Variable station kun je gebruiken om het relevante station er uit te plukken. Conversie naar beaufort, knopen en/of km/u voor wind niet erin gezet.
Tijden zijn omgezet in epoch formaat tbv influxdb.

[{"id":"ee5ec95b.d2b468","type":"inject","z":"c371a104.bf6be","name":"make request","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":150,"y":360,"wires":[["6757076d.a2c7b8"]]},{"id":"6757076d.a2c7b8","type":"http request","z":"c371a104.bf6be","name":"","method":"GET","ret":"txt","paytoqs":false,"url":"https://data.buienradar.nl/2.0/feed/json","tls":"","persist":false,"proxy":"","authType":"","x":150,"y":460,"wires":[["9594244b.40a9f8"]]},{"id":"ad480648.d5d1b8","type":"debug","z":"c371a104.bf6be","name":"","active":true,"console":"false","complete":"false","x":490,"y":460,"wires":[]},{"id":"9594244b.40a9f8","type":"json","z":"c371a104.bf6be","name":"","property":"payload","action":"","pretty":false,"x":130,"y":540,"wires":[["ad480648.d5d1b8","3e437ae6.968d16"]]},{"id":"3e437ae6.968d16","type":"function","z":"c371a104.bf6be","name":"Adapt Message","func":"var station = 4;\n\nvar timestamp = new Date(msg.payload.actual.stationmeasurements[station].timestamp);\ntimestamp = timestamp.getTime()*1000000;\n\nvar sunrise = new Date(msg.payload.actual.sunrise);\nsunrise = sunrise.getTime()*1000000;\n\nvar sunset = new Date(msg.payload.actual.sunset);\nsunset = sunset.getTime()*1000000;\n\nvar stationid = msg.payload.actual.stationmeasurements[station].stationid;\nvar stationname = msg.payload.actual.stationmeasurements[station].stationname;\nvar winddirection = msg.payload.actual.stationmeasurements[station].winddirection;\nvar airpressure = msg.payload.actual.stationmeasurements[station].airpressure;\nvar temperature = msg.payload.actual.stationmeasurements[station].temperature;\nvar groundtemperature = msg.payload.actual.stationmeasurements[station].groundtemperature;\nvar feeltemperature = msg.payload.actual.stationmeasurements[station].feeltemperature;\nvar visibility = msg.payload.actual.stationmeasurements[station].visibility;\nvar windgusts = msg.payload.actual.stationmeasurements[station].windgusts;\nvar windspeed = msg.payload.actual.stationmeasurements[station].windspeed;\nvar humidity = msg.payload.actual.stationmeasurements[station].humidity;\nvar precipitation = msg.payload.actual.stationmeasurements[station].precipitation;\nvar sunpower = msg.payload.actual.stationmeasurements[station].sunpower;\nvar rainFallLast24Hour = msg.payload.actual.stationmeasurements[station].rainFallLast24Hour;\nvar rainFallLastHour = msg.payload.actual.stationmeasurements[station].rainFallLastHour;\nvar winddirectiondegrees = msg.payload.actual.stationmeasurements[station].winddirectiondegrees;\n\nmsg.payload = {};\nmsg.payload.time = timestamp; \nmsg.payload.sunrise = sunrise;\nmsg.payload.sunset = sunset;\nmsg.payload.stationid = stationid;\nmsg.payload.stationname = stationname;\nmsg.payload.windrichting = winddirection;\nmsg.payload.luchtdruk = airpressure;\nmsg.payload.temperatuurGC = temperature;\nmsg.payload.grondtemperatuurGC = groundtemperature;\nmsg.payload.gevoelstemperatuurGC = feeltemperature;\nmsg.payload.zichtmeters = visibility;\nmsg.payload.windstotenMS = windgusts;\nmsg.payload.windsnelheidMS = windspeed;\nmsg.payload.luchtvochtigheid = humidity;\nmsg.payload.neerslag = precipitation;\nmsg.payload.windrichtingDG = winddirectiondegrees;\nmsg.payload.regen1h = rainFallLastHour;\nmsg.payload.regen24h = rainFallLast24Hour;\nmsg.payload.zonneintensiteitWM2 = sunpower;\n\nreturn msg;","outputs":1,"noerr":0,"x":500,"y":540,"wires":[["2f53f657.f13d6a"]]},{"id":"2f53f657.f13d6a","type":"debug","z":"c371a104.bf6be","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":760,"y":540,"wires":[]}]

**Comment by dkijkuit** [comment]
Ik heb het gezien inderdaad. Van buienradar heb ik nog geen reactie ontvangen, maar ik ga de node omzetten naar de JSON variant.

**Comment by dkijkuit** [comment]
@coolbox13 De node is aangepast om de JSON feed te gebruiken. Je hoeft alleen de buienradar.js naar je lokale Node-Red installatie te kopiëren om te testen. Laat even weten of dit werkt.

Commit 14fbead2833fd44a10c152715843137b1ee953cf

**Comment by coolbox13** [comment]
Ik ga even kijken hoe ik dat doe; mijn node red draait in een docker container.

**Comment by coolbox13** [comment]
Was even zoeken waar ik hem moest vinden in de container, maar het is gelukt..:)) Dus hij werkt.
Zag dat er wel wat extra info aanwezig is in de buienradar info. Ga toch ook eens naar jou code kijken. Zitten nog wat leuke dingen in.

Gr. Herman
