### ISSUE TITLE
belgian version

### ISSUE THREAD

**Issue by unbreakmat** [dkijkuit/node-red-contrib-buienradar#15]
Hoi dkijkuit

Zou het mogelijk zijn om ook data te kunnen pullen van belgie?
Zodat een belgisch weerbericht ook mogelijk is?
misschien door weerstations van belgie toe te voegen als dat mogelijk is?
Ik vond je node red super maa rik woon niet in nederland, maar belgie
Zou dus super zijn moest je deze (kleine) aanpassing kunnen doen!!

**Comment by dkijkuit** [comment]
Op zich geen probleem, maar volgens mij is er geen JSON feed van buienradar.be

**Comment by unbreakmat** [comment]
8k heb de vraag gesteld aan buienradar zelf of deze beschikbaar is de json, ik laat je meer weten hier vanaf ik antwoord krijg
