### ISSUE TITLE
 TypeError: Cannot set property 'titel' of undefined

### ISSUE THREAD

**Issue by nachtbraker** [dkijkuit/node-red-contrib-buienradar#19]
I have just installed this plugin and it works great except for one thing: each time when the data is fetched and parsed from buienradar.nl I get this message in the log file:

16 Jun 10:11:09 - [info] [buienradar:WijkAanZee] Error: TypeError: Cannot set property 'titel' of undefined

**Comment by dkijkuit** [comment]
Fixed 8404012011552365aea5d350e2eabd02db96f583
