### ISSUE TITLE
windsnelheidBF = windsnelheidMS ?

### ISSUE THREAD

**Issue by satoer** [dkijkuit/node-red-contrib-buienradar#20]
It looks like the attribute "windsnelheidBF" gets its data from "windsnelheidMS"? These are always the same. Thought I was in a hurricane ;)

**Comment by dkijkuit** [comment]
Fixed 7e061b502101d8c7b6ea62f8613f1745340bdeb6

**Comment by satoer** [comment]
Thanks!
