### ISSUE TITLE
Error: getaddrinfo EAI_AGAIN data.buienradar.nl data.buienradar.nl:443

### ISSUE THREAD

**Issue by satoer** [dkijkuit/node-red-contrib-buienradar#22]
Hi, suddenly the node gives me this error (line of text under the node):
**Error: getaddrinfo EAI_AGAIN data.buienradar.nl data.buienradar.nl:443**
Any idea what's wrong?

Thanks for reading, Cheers Michel.

**Comment by dkijkuit** [comment]
This appears to be unrelated to the node. Just ran a test, no issues here. The error you receive appears to be caused by networking issues.

**Comment by satoer** [comment]
Well, I did recently added a Asus router (to replace the routing from my modem) to the network. Don't know if then the problem started. But it might be related. Can't seem to fix it though. Disabled the firewall, "AI protection", even enabled (for testing purposes) all the ports (forwarding) to the NAS (Node red runs inside docker on a Synology NAS). Still the same error. If you have any clue for me where to look, please let me know. Ill do some more investigation.

Anyhow, thanks for the reply.

**Comment by dkijkuit** [comment]
It sounds like a docker DNS issue in that case. You could try to [exec](https://docs.docker.com/engine/reference/commandline/exec/) a bash shell in the running container and check with [curl](https://curl.se/) if the container is able to access the destination.

**Comment by satoer** [comment]
Thanks for the clue David! I resolved the problem. Turns out the gateway setting inside the Synology settings was still pointing to the old IP-adress (from the modem). It's working again!
