### ISSUE TITLE
WIndsnelheid BF = Winsnelheid m/s not fixed when installing using Manage Palette

### ISSUE THREAD

**Issue by Dunnenj** [dkijkuit/node-red-contrib-buienradar#23]
Windsnelheid BF = Windsnelheid m/sisfixed according https://github.com/dkijkuit/node-red-contrib-buienradar/issues/20.

However this issue is still there. Installed the contrib using the palette function.

---
John

**Comment by dkijkuit** [comment]
Issue was closed with version 0.4.3, but node-red changed publication procedures. Each update has to requested manually apparently. I requested to publish the latest version, should be fixed now.

> As of April 2020, the the Node-RED Flow Library is no longer able to automatically index and update nodes published on npm with the node-red keyword. Instead, a submission request has to be placed manually.
 
https://nodered.org/docs/creating-nodes/packaging

**Comment by Dunnenj** [comment]
Thanks this did work.
