### ISSUE TITLE
Buienradar Node-Red gives payload without content

### ISSUE THREAD

**Issue by MarkRoks** [dkijkuit/node-red-contrib-buienradar#25]
Hello,

Recently I no longer receive a payload with content from the Node-Red Buienradar node. I have tried to select another weather station, but it does not give a payload with payload (anymore).

What could it be about? 

I like to hear it.

Greetings,

**Comment by Gjaltz** [comment]
It looks that it works with some interupts . Now I recieve data.

**Comment by MarkRoks** [comment]
I receive also data at this moment. This morning I saw only payload without content...

Does this problem arise from Buienradar, or the Node self?

**Comment by nachtbraker** [comment]
You can check the URL manually to see if it's an issue with Buienrader or the node. The link it uses is https://data.buienradar.nl//2.0/feed/json

**Comment by dkijkuit** [comment]
If everything seems to be working again, I'm going to close this issue. In case it happens again, be sure the check the buienradar url first.
